added checking logs

diff --git a/.github/workflows/build-and-test.yaml b/.github/workflows/build-and-test.yaml
--- a/.github/workflows/build-and-test.yaml
+++ b/.github/workflows/build-and-test.yaml
@@ -73,6 +73,14 @@ jobs:
             -p 44044:44044 \
             rshelekhov/grpc-sso:latest
 
+      - name: Check container status and logs if it failed
+        run: |
+          if [ "$(docker inspect -f {{.State.Running}} grpc-sso-service)" != "true" ]; then
+            echo "Container grpc-sso-service failed to start. Displaying logs:"
+            docker logs grpc-sso-service
+            exit 1
+          fi
+
       - name: Wait for services to be ready
         run: sleep 20
 
